### ISSUE TITLE
high CPU if no beacons

### ISSUE THREAD

**Issue by jswim788** [daemondazz/vera-presence-scanner#6]
I think there is a bug if there are no beacons.  In that case, the next_beacon_scan time never gets updated.  That means that at line 330 of run_scanner.py, the condition will always be true, line 335 will always get a negative number, and in line 336, it will never sleep.

I suggest that at line 330, add an AND with known_beacons.  Then it will only update next_event to next_beacon_scan if there are any beacons to be scanned.

**Comment by GeekGoneOld** [comment]
Perfect solution.  Thanks.  Will be posted within 24 hours.

**Comment by GeekGoneOld** [comment]
Fixed by today's commit
